# backend/src/api/main.py

import os
from typing import Any, Dict, Optional

import pandas as pd
import pdfplumber
from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware

from src.transcript_ingestion import parse_transcript_text
from src.skill_aggregation_from_parsed import build_skill_profile_from_parsed

from pydantic import BaseModel
from typing import List, Optional



app = FastAPI(
    title="Transcript-based Skill Validation API",
    version="0.3.1",
)

origins = [
    "http://127.0.0.1:5500",
    "http://localhost:5500",
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_methods=["*"],
    allow_headers=["*"],
)

class PrepareQuizRequest(BaseModel):
    selected_skills: List[str] = []
    num_questions_per_skill: int = 3
    difficulty: str = "mixed"   # optional: "easy" | "medium" | "hard" | "mixed"


def load_role_readiness() -> pd.DataFrame:
    """
    Loads the role readiness summary CSV (top roles with overall readiness score).
    """
    path = os.path.join("output", "role_readiness_dynamic.csv")
    if not os.path.exists(path):
        raise FileNotFoundError("Role readiness CSV not found. Run job_role_model_dynamic.py first.")
    return pd.read_csv(path)


def load_skill_explanations() -> pd.DataFrame:
    """
    Loads a CSV that contains explainability columns for skills.
    Tries multiple candidate files.
    """
    candidates = [
        "output/skill_explanations.csv",
        "output/skill_profiles_explainable.csv",
    ]
    for p in candidates:
        if os.path.exists(p):
            return pd.read_csv(p)
    raise FileNotFoundError("No explainability file found. Generate explainable skill output first.")


def load_role_readiness_details() -> pd.DataFrame:
    """
    Loads the role readiness details CSV (per-skill breakdown for each role).
    """
    candidates = [
        "output/role_readiness_details_dynamic.csv",
        "output/role_readiness_details_explainable.csv",
    ]
    for p in candidates:
        if os.path.exists(p):
            return pd.read_csv(p)
    raise FileNotFoundError("Role readiness details file not found. Run job_role_model_dynamic.py first.")


@app.post("/students/{student_id}/upload-transcript")
async def upload_transcript(student_id: str, file: UploadFile = File(...)):
    try:
        os.makedirs("output", exist_ok=True)

        contents = await file.read()
        tmp_path = os.path.join("output", f"_tmp_{student_id}_{file.filename}")
        with open(tmp_path, "wb") as f:
            f.write(contents)

        # PDF only (for now)
        if not file.filename.lower().endswith(".pdf"):
            raise HTTPException(status_code=400, detail="Only PDF supported for now.")

        text_parts = []
        with pdfplumber.open(tmp_path) as pdf:
            for page in pdf.pages:
                text_parts.append(page.extract_text() or "")
        text = "\n".join(text_parts)

        details, courses_df = parse_transcript_text(text)

        if courses_df.empty:
            raise HTTPException(
                status_code=422,
                detail="No course lines detected. Transcript format may not match parser regex.",
            )

        skills_df = build_skill_profile_from_parsed(
            student_id=student_id,
            parsed_courses_df=courses_df,
            mapping_path="input/course_skill_mapping.csv",
        )

        # Persist per-student skill profile so GET /skills works immediately
        per_student_path = os.path.join("output", f"skill_profile_{student_id}.csv")
        try:
            skills_df.to_csv(per_student_path, index=False)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to write {per_student_path}: {e}")

        return {
            "student_id": student_id,
            "transcript_details": details,
            "num_courses_detected": int(len(courses_df)),
            "courses": courses_df.to_dict(orient="records"),
            "num_skills_mapped": int(len(skills_df)),
            "skills": skills_df.sort_values("ScoreNormalized", ascending=False).to_dict(orient="records"),
            "saved_skill_profile": os.path.basename(per_student_path),
        }

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error processing transcript: {e}")
    finally:
        # Keep temp by default. If you want auto-delete, uncomment this.
        # if os.path.exists(tmp_path):
        #     try:
        #         os.remove(tmp_path)
        #     except Exception:
        #         pass
        pass


@app.get("/students/{student_id}/skills")
def get_student_skills(student_id: str):
    """
    Returns the student's skill profile.
    Priority:
      0) output/skill_profile_{student_id}.csv (generated by upload-transcript)
      1) output/skill_profiles_with_quiz.csv
      2) output/skill_profiles_explainable.csv
    """
    per_student_path = os.path.join("output", f"skill_profile_{student_id}.csv")
    path_primary = os.path.join("output", "skill_profiles_with_quiz.csv")
    path_fallback = os.path.join("output", "skill_profiles_explainable.csv")

    # 0) Per-student file from upload transcript
    if os.path.exists(per_student_path):
        df = pd.read_csv(per_student_path)
        if "ScoreNormalized" in df.columns:
            df = df.sort_values("ScoreNormalized", ascending=False)
        return {
            "student_id": student_id,
            "source_file": os.path.basename(per_student_path),
            "skills": df.to_dict(orient="records"),
        }

    # 1) Global files fallback
    path = path_primary if os.path.exists(path_primary) else path_fallback
    if not os.path.exists(path):
        raise HTTPException(status_code=404, detail="Skill profile CSV not found in output/")

    df = pd.read_csv(path)

    col = "StudentID" if "StudentID" in df.columns else ("student_id" if "student_id" in df.columns else None)
    if col is None:
        raise HTTPException(status_code=500, detail=f"Student id column not found in {os.path.basename(path)}")

    student_df = df[df[col].astype(str) == str(student_id)].copy()
    if student_df.empty:
        raise HTTPException(
            status_code=404,
            detail="Student not found in skill profile. Upload transcript first or generate the global CSV.",
        )

    for score_col in ["FinalScore", "ScoreNormalized", "Score"]:
        if score_col in student_df.columns:
            student_df = student_df.sort_values(score_col, ascending=False)
            break

    return {
        "student_id": student_id,
        "source_file": os.path.basename(path),
        "skills": student_df.to_dict(orient="records"),
    }


@app.get("/students/{student_id}/roles")
def get_student_roles(student_id: str):
    """
    Returns role readiness results for a student from output CSV.
    Note: This reads the global role readiness file generated by your pipeline.
    """
    path = os.path.join("output", "role_readiness_dynamic.csv")
    if not os.path.exists(path):
        raise HTTPException(status_code=404, detail="Role readiness CSV not found in output/")

    df = pd.read_csv(path)

    col = "StudentID" if "StudentID" in df.columns else ("student_id" if "student_id" in df.columns else None)
    if col is None:
        raise HTTPException(status_code=500, detail="Student id column not found in role readiness CSV")

    student_df = df[df[col].astype(str) == str(student_id)].copy()
    if student_df.empty:
        raise HTTPException(
            status_code=404,
            detail="Student not found in role readiness. Run role model pipeline for this student.",
        )

    for readiness_col in ["ReadinessScore", "RoleReadiness", "Score", "MatchScore"]:
        if readiness_col in student_df.columns:
            student_df = student_df.sort_values(readiness_col, ascending=False)
            break

    return {
        "student_id": student_id,
        "source_file": os.path.basename(path),
        "roles": student_df.to_dict(orient="records"),
    }


@app.get("/students/{student_id}/xai/skills")
def xai_skills(student_id: str, top_n: int = 15) -> Dict[str, Any]:
    try:
        df = load_skill_explanations()
    except FileNotFoundError as e:
        raise HTTPException(status_code=500, detail=str(e))

    # safer matching (handles numeric IDs in CSV)
    if "StudentID" not in df.columns:
        raise HTTPException(status_code=500, detail="StudentID column missing in skill explanations file.")

    df_s = df[df["StudentID"].astype(str) == str(student_id)].copy()
    if df_s.empty:
        raise HTTPException(status_code=404, detail=f"No explainability found for student {student_id}")

    score_col = "FinalScore" if "FinalScore" in df_s.columns else ("ScoreNormalized" if "ScoreNormalized" in df_s.columns else None)
    if score_col:
        df_s = df_s.sort_values(score_col, ascending=False).head(int(top_n))
    else:
        df_s = df_s.head(int(top_n))

    evidence_cols = [c for c in ["Evidence", "EvidenceCourses", "CourseEvidence", "MatchedCourses"] if c in df_s.columns]

    out = []
    for _, r in df_s.iterrows():
        evidence_text = ""
        if evidence_cols:
            evidence_text = str(r[evidence_cols[0]])

        out.append(
            {
                "skill": str(r.get("Skill", "")),
                "score": float(r[score_col]) if score_col and pd.notna(r[score_col]) else None,
                "level": str(r["FinalSkillLevel"]) if "FinalSkillLevel" in df_s.columns else str(r.get("SkillLevel", "")),
                "evidence": evidence_text,
            }
        )

    return {"student_id": student_id, "count": len(out), "skills": out}


@app.get("/students/{student_id}/xai/roles")
def xai_roles(student_id: str, role: Optional[str] = None, top_n: int = 1) -> Dict[str, Any]:
    try:
        df = load_role_readiness_details()
    except FileNotFoundError as e:
        raise HTTPException(status_code=500, detail=str(e))

    if "StudentID" not in df.columns:
        raise HTTPException(status_code=500, detail="StudentID column missing in role readiness details file.")

    df_s = df[df["StudentID"].astype(str) == str(student_id)].copy()
    if df_s.empty:
        raise HTTPException(status_code=404, detail=f"No role details found for student {student_id}")

    # If role not provided, pick the top role from summary if possible
    if role is None:
        try:
            summary = load_role_readiness()
            if "StudentID" in summary.columns:
                s = summary[summary["StudentID"].astype(str) == str(student_id)].copy()
                if not s.empty:
                    readiness_col = "ReadinessScore" if "ReadinessScore" in s.columns else None
                    if readiness_col:
                        s = s.sort_values(readiness_col, ascending=False)
                    if "RoleName" in s.columns:
                        role = str(s.iloc[0]["RoleName"])
        except Exception:
            # fallback to first role in details
            if "RoleName" in df_s.columns and not df_s.empty:
                role = str(df_s.iloc[0]["RoleName"])

    if role and "RoleName" in df_s.columns:
        df_r = df_s[df_s["RoleName"].astype(str) == str(role)].copy()
    else:
        df_r = df_s.copy()

    if df_r.empty:
        raise HTTPException(status_code=404, detail=f"No detail rows for role '{role}' and student {student_id}")

    required_col = "RequiredImportance" if "RequiredImportance" in df_r.columns else None
    student_score_col = "StudentScore" if "StudentScore" in df_r.columns else None
    weak_col = "IsWeakOrMissing" if "IsWeakOrMissing" in df_r.columns else None

    rows = []
    for _, r in df_r.iterrows():
        rows.append(
            {
                "skill": str(r.get("Skill", "")),
                "required_importance": float(r[required_col]) if required_col and pd.notna(r.get(required_col)) else None,
                "student_score": float(r[student_score_col]) if student_score_col and pd.notna(r.get(student_score_col)) else None,
                "student_level": str(r.get("StudentLevel", "")),
                "attained_fraction": float(r["AttainedFraction"]) if "AttainedFraction" in df_r.columns and pd.notna(r.get("AttainedFraction")) else None,
                "is_weak_or_missing": bool(r[weak_col]) if weak_col and pd.notna(r.get(weak_col)) else None,
            }
        )

    weak_count = sum(1 for x in rows if x.get("is_weak_or_missing"))

    # Optional: show only top_n required skills (by required_importance) if top_n is provided
    if top_n is not None and int(top_n) > 0:
        rows_sorted = sorted(
            rows,
            key=lambda x: (x["required_importance"] if x["required_importance"] is not None else -1.0),
            reverse=True,
        )
        rows = rows_sorted[: int(top_n)] if role is None else rows  # keep full list when explaining a chosen role

    return {
        "student_id": student_id,
        "role_name": role,
        "num_required_skills": len(rows),
        "num_weak_or_missing": weak_count,
        "required_skills": rows,
    }

@app.post("/students/{student_id}/prepare-quiz")
def prepare_quiz(student_id: str, payload: PrepareQuizRequest):
    # 1) validate selection count
    selected = [s.strip() for s in payload.selected_skills if s and s.strip()]
    if not selected:
        raise HTTPException(status_code=400, detail="Please select at least 1 skill.")
    if len(selected) > 5:
        raise HTTPException(status_code=400, detail="You can select a maximum of 5 skills.")

    # 2) validate selected skills are in student's inferred skills
    per_student_path = os.path.join("output", f"skill_profile_{student_id}.csv")
    if not os.path.exists(per_student_path):
        raise HTTPException(status_code=404, detail="Upload transcript first (skill profile not found).")

    skills_df = pd.read_csv(per_student_path)
    if "Skill" not in skills_df.columns:
        raise HTTPException(status_code=500, detail="Skill profile missing 'Skill' column.")

    available = set(skills_df["Skill"].astype(str))
    invalid = [s for s in selected if s not in available]
    if invalid:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid skills selected: {invalid}. Must be from inferred skills list.",
        )

    # 3) load generated questions (you already generate this in your pipeline)
    qpath = os.path.join("output", "quiz_questions_generated.csv")
    if not os.path.exists(qpath):
        raise HTTPException(
            status_code=404,
            detail="quiz_questions_generated.csv not found. Run quiz_generation_rag.py or build a question bank.",
        )

    qdf = pd.read_csv(qpath)

    # find the skill column used in your question file
    skill_col = None
    for c in ["Skill", "TargetSkill", "skill"]:
        if c in qdf.columns:
            skill_col = c
            break
    if skill_col is None:
        raise HTTPException(status_code=500, detail="Quiz question file has no Skill/TargetSkill column.")

    # optional difficulty filtering if your file has it
    diff_col = None
    for c in ["TargetDifficulty", "Difficulty", "difficulty"]:
        if c in qdf.columns:
            diff_col = c
            break

    quiz_questions = []
    per_skill = int(payload.num_questions_per_skill)

    for skill in selected:
        subset = qdf[qdf[skill_col].astype(str) == skill].copy()

        if diff_col and payload.difficulty.lower() != "mixed":
            subset = subset[subset[diff_col].astype(str).str.lower() == payload.difficulty.lower()]

        if subset.empty:
            continue

        # sample questions
        subset = subset.sample(n=min(per_skill, len(subset)), random_state=42)

        quiz_questions.extend(subset.to_dict(orient="records"))

    if not quiz_questions:
        raise HTTPException(
            status_code=404,
            detail="No questions found for selected skills. Try mixed difficulty or generate more questions.",
        )

    return {
        "student_id": student_id,
        "selected_skills": selected,
        "num_questions": len(quiz_questions),
        "questions": quiz_questions,
    }
